// Copyright 2014 Rana Ian. All rights reserved.
// Use of this source code is governed by The MIT License
// found in the accompanying LICENSE file.

package ora

/*
#include <stdlib.h>
#include <oci.h>
#include "version.h"
*/
import "C"
import "unsafe"

// Generate all the def[IU]int{8,16,32,32}.go from defInt32.go
//
// Generated by go run gen.go

type defInt32 struct {
	ociDef
	ociNumber  []C.OCINumber
	isNullable bool
}

func (def *defInt32) define(position int, isNullable bool, rset *Rset) error {
	def.rset = rset
	def.isNullable = isNullable
	if def.ociNumber != nil {
		C.free(unsafe.Pointer(&def.ociNumber[0]))
	}
	def.ociNumber = (*((*[MaxFetchLen]C.OCINumber)(C.malloc(C.size_t(rset.fetchLen) * C.sizeof_OCINumber))))[:rset.fetchLen]
	return def.ociDef.defineByPos(position, unsafe.Pointer(&def.ociNumber[0]), C.sizeof_OCINumber, C.SQLT_VNU)
}

func (def *defInt32) value(offset int) (value interface{}, err error) {
	if def.isNullable {
		oraInt32Value := Int32{IsNull: def.nullInds[offset] < 0}
		if !oraInt32Value.IsNull {
			on := def.ociNumber[offset]
			r := C.OCINumberToInt(
				def.rset.stmt.ses.srv.env.ocierr, //OCIError              *err,
				&on,                                  //const OCINumber       *number,
				byteWidth32,                          //uword                 rsl_length,
				C.OCI_NUMBER_SIGNED,                  //uword                 rsl_flag,
				unsafe.Pointer(&oraInt32Value.Value)) //void                  *rsl );
			if r == C.OCI_ERROR {
				err = def.rset.stmt.ses.srv.env.ociError()
			}
		}
		value = oraInt32Value
	} else {
		var int32Value int32
		//if !def.nullp.IsNull() {
		if def.nullInds[offset] >= 0 {
			on := def.ociNumber[offset]
			r := C.OCINumberToInt(
				def.rset.stmt.ses.srv.env.ocierr, //OCIError              *err,
				&on,                         //const OCINumber       *number,
				byteWidth32,                 //uword                 rsl_length,
				C.OCI_NUMBER_SIGNED,         //uword                 rsl_flag,
				unsafe.Pointer(&int32Value)) //void                  *rsl );
			if r == C.OCI_ERROR {
				err = def.rset.stmt.ses.srv.env.ociError()
			}
		}
		value = int32Value
	}
	return value, err
}

func (def *defInt32) alloc() error {
	return nil
}

func (def *defInt32) free() {
}

func (def *defInt32) close() (err error) {
	defer func() {
		if value := recover(); value != nil {
			err = errR(value)
		}
	}()
	rset := def.rset
	def.rset = nil
	def.ocidef = nil
	if def.ociNumber != nil {
		C.free(unsafe.Pointer(&def.ociNumber[0]))
		def.ociNumber = nil
	}
	def.arrHlp.close()
	rset.putDef(defIdxInt32, def)
	return nil
}
